// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5f7gRMd66t1cLq8-zqEAGrJji-cmoMI0',
    appId: '1:648570023243:web:458d9c343d7687dbdb0cce',
    messagingSenderId: '648570023243',
    projectId: 'chat-app-66b94',
    authDomain: 'chat-app-66b94.firebaseapp.com',
    storageBucket: 'chat-app-66b94.firebasestorage.app',
    measurementId: 'G-P29WQLQ1QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYKFbM65uiRsF5PR5KzojMgp8D-PDamgM',
    appId: '1:648570023243:android:2d74bb6787ffcce7db0cce',
    messagingSenderId: '648570023243',
    projectId: 'chat-app-66b94',
    storageBucket: 'chat-app-66b94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsjnivqzVF8I_CdMetPxL7XvQn9HKiuoY',
    appId: '1:648570023243:ios:e66b01086f339436db0cce',
    messagingSenderId: '648570023243',
    projectId: 'chat-app-66b94',
    storageBucket: 'chat-app-66b94.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsjnivqzVF8I_CdMetPxL7XvQn9HKiuoY',
    appId: '1:648570023243:ios:e66b01086f339436db0cce',
    messagingSenderId: '648570023243',
    projectId: 'chat-app-66b94',
    storageBucket: 'chat-app-66b94.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5f7gRMd66t1cLq8-zqEAGrJji-cmoMI0',
    appId: '1:648570023243:web:1a2ba9c34eb6693bdb0cce',
    messagingSenderId: '648570023243',
    projectId: 'chat-app-66b94',
    authDomain: 'chat-app-66b94.firebaseapp.com',
    storageBucket: 'chat-app-66b94.firebasestorage.app',
    measurementId: 'G-RRQ5JYPJYL',
  );

}